/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CartaoJogoPrincipal: typeof import('./components/sports/CartaoJogoPrincipal.vue')['default']
    CartaoPartida: typeof import('./components/CartaoPartida.vue')['default']
    CartaoPartidaAlt: typeof import('./components/sports/CartaoPartidaAlt.vue')['default']
    DisplayJogos: typeof import('./components/sports/DisplayJogos.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HorizontalCardsDisplay: typeof import('./components/sports/HorizontalCardsDisplay.vue')['default']
    NavbarHorizontalOverlay: typeof import('./components/NavbarHorizontalOverlay.vue')['default']
    NavbarSports: typeof import('./components/sports/NavbarSports.vue')['default']
    NavbarVerticalOverlay: typeof import('./components/NavbarVerticalOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
